name: balebale_cabs
description: A cab pooling application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.4.9
  go_router: ^15.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  intl: ^0.20.2
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.1
  lints: ^6.0.0
  material_color_utilities: 0.11.1
  meta: 1.16.0
  test_api: 0.7.4
  unicode: ^0.3.1
  vector_math: 2.1.4
  vm_service: 15.0.0
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  leak_tracker: 10.0.9
  leak_tracker_flutter_testing: 3.0.9
